"""added celery_task_execution table

Revision ID: 384fe9c0050e
Revises: 64a57d36a678
Create Date: 2026-05-11 03:50:01.410070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '384fe9c0050e'
down_revision: Union[str, None] = '64a57d36a678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_execution',
    sa.Column('execution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_arg_hash', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index('idx_celery_task_execution_created_at', 'celery_task_execution', ['created_at'], unique=False)
    op.create_index('idx_celery_task_execution_status', 'celery_task_execution', ['status'], unique=False)
    op.create_index('idx_celery_task_id', 'celery_task_execution', ['celery_task_id'], unique=False)
    op.create_index('idx_task_name_args_hash', 'celery_task_execution', ['task_name', 'task_arg_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_name_args_hash', table_name='celery_task_execution')
    op.drop_index('idx_celery_task_id', table_name='celery_task_execution')
    op.drop_index('idx_celery_task_execution_status', table_name='celery_task_execution')
    op.drop_index('idx_celery_task_execution_created_at', table_name='celery_task_execution')
    op.drop_table('celery_task_execution')
    # ### end Alembic commands ###
