"""udate celery_task_execution tbale indexes

Revision ID: 77054c0e5f00
Revises: 384fe9c0050e
Create Date: 2026-05-11 19:12:53.219741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77054c0e5f00'
down_revision: Union[str, None] = '384fe9c0050e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_name_args_hash', table_name='celery_task_execution')
    op.create_index('idx_task_name_args_hash_celery_task_id', 'celery_task_execution', ['task_name', 'task_arg_hash', 'celery_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_name_args_hash_celery_task_id', table_name='celery_task_execution')
    op.create_index('idx_task_name_args_hash', 'celery_task_execution', ['task_name', 'task_arg_hash'], unique=True)
    # ### end Alembic commands ###
