"""New migration comment

Revision ID: be28c12c36cf
Revises: c3d4e5f6a7b8
Create Date: 2026-08-22 04:58:25.252182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be28c12c36cf'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_deleted_at', table_name='assets')
    op.drop_index('ix_assets_is_latest', table_name='assets')
    op.create_index('ix_asset_deleted_at', 'assets', ['deleted_at'], unique=False)
    op.create_index('ix_asset_is_latest', 'assets', ['is_latest'], unique=False)
    op.drop_index('ix_chunks_deleted_at', table_name='chunks')
    op.create_index('ix_chunk_deleted_at', 'chunks', ['deleted_at'], unique=False)
    op.alter_column('query_logs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('monthly_llm_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_llm_budget')
    op.alter_column('query_logs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_chunk_deleted_at', table_name='chunks')
    op.create_index('ix_chunks_deleted_at', 'chunks', ['deleted_at'], unique=False)
    op.drop_index('ix_asset_is_latest', table_name='assets')
    op.drop_index('ix_asset_deleted_at', table_name='assets')
    op.create_index('ix_assets_is_latest', 'assets', ['is_latest'], unique=False)
    op.create_index('ix_assets_deleted_at', 'assets', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
